debug:
  config: true
  death: false
  spawn:
    natural: false

world:
  name: world
  border: 3490

leprechaun:
  can_despawn: true
  chance: 1.0
  health: 25
  baby_chance: 0.2
  villager_chance: 0.3
  weapon_drop_chance: 0.05
  armour:
    worn: false
    drop_chance: 0.0075

pots:
  # Chance of a pot of gold spawning upon leprechaun death.
  chance: 0.03

  # Maximum number of pots of gold allowed in the world simultaneously.
  max: 30

  # Range of distances from leprechaun death point that a pot will spawn.
  range:
    min: 100
    max: 300

  # Extra ticks of time given to the player to find the pot.
  extra_ticks: 800

  # Pot will exist in the world for range / min_player_speed seconds.
  # The player must move faster than this to reach the pot in time.
  min_player_speed: 3.0

  map:
    name: '&6Treasure at {0}'
    lore: 'Aye, ye got me!|Me treasure is at {0}.|But ye better shake a leg!|Nothing lasts forever.'

  particle:
    radius: 1.25
    count: 25


drops:
  regular:
    gold_nugget:
      chance: 0.05
      min: 1
      max: 3
      item:
        ==: org.bukkit.inventory.ItemStack
        type: GOLD_NUGGET
    potato:
      chance: 0.05
      item:
        ==: org.bukkit.inventory.ItemStack
        type: POTATO_ITEM
    baked_potato:
      chance: 0.05
      item:
        ==: org.bukkit.inventory.ItemStack
        type: BAKED_POTATO
    rotten_potato:
      chance: 0.05
      item:
        ==: org.bukkit.inventory.ItemStack
        type: POISONOUS_POTATO

  special:
    gold_ingot:
      chance: 0.1
      item:
        ==: org.bukkit.inventory.ItemStack
        type: GOLD_INGOT
    whiskey:
      chance: 0.01
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: minecraft:luck
          display-name: §6Whiskey
          custom-effects:
          - ==: PotionEffect
            effect: 15
            duration: 600
            amplifier: 1
            ambient: true
            has-particles: true
            has-icon: true
          - ==: PotionEffect
            effect: 9
            duration: 1200
            amplifier: 1
            ambient: true
            has-particles: true
            has-icon: true
    guinness:
      chance: 0.01
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          potion-type: minecraft:luck
          display-name: §fGuinness
          custom-effects:
          - ==: PotionEffect
            effect: 6
            duration: 1
            amplifier: 0
            ambient: true
            has-particles: true
          - ==: PotionEffect
            effect: 15
            duration: 1200
            amplifier: 1
            ambient: true
            has-particles: true

  pots:
    gold_helmet:
      chance: 0.1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: GOLDEN_HELMET
    gold_chestplate:
      chance: 0.1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: GOLDEN_CHESTPLATE
    gold_leggings:
      chance: 0.1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: GOLDEN_LEGGINGS
    gold_boots:
      chance: 0.1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: GOLDEN_BOOTS
    gold_axe:
      chance: 0.1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: GOLDEN_AXE
    gold_sword:
      chance: 0.1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: GOLDEN_SWORD
    watch:
      chance: 0.1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: CLOCK
    gold_nugget:
      chance: 1.0
      min: 3
      max: 6
      item:
        ==: org.bukkit.inventory.ItemStack
        type: GOLD_NUGGET
    gold_ingot:
      chance: 1.0
      min: 2
      max: 4
      item:
        ==: org.bukkit.inventory.ItemStack
        type: GOLD_INGOT
    gold_block:
      chance: 0.1
      item:
        ==: org.bukkit.inventory.ItemStack
        type: GOLD_BLOCK
    gold_barding:
      chance: 0.1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: GOLDEN_HORSE_ARMOR
    golden_apple:
      chance: 0.2
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: GOLDEN_APPLE
    notch_apple:
      chance: 0.1
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: ENCHANTED_GOLDEN_APPLE
    golden_carrot:
      chance: 0.4
      min: 1
      max: 3
      item:
        ==: org.bukkit.inventory.ItemStack
        type: GOLDEN_CARROT
    doubloon:
      chance: 0.333
      item:
        ==: org.bukkit.inventory.ItemStack
        v: 1631
        type: SUNFLOWER
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §eDoubloon §d[SUPER RARE]
          lore:
          - §6Ah, gold! A pirate's best friend. Just don't look too closely.
          - Trade this precious booty at spawn!
          enchants:
            ARROW_INFINITE: 1

messages:
  names:
    colour: '&2'
    first:
    - Aidan
    - Conor
    - Declan
    - Donal
    - Dougal
    - Fergal
    - Finn
    - Kieran
    - Liam
    - Paddy
    - Patrick
    - Rory
    - Ryan
    - Seamus
    - Sean

    surname:
    - Fitzgerald
    - Fitzpatrick
    - Flanagan
    - Kelly
    - McStereotype
    - McCormack
    - McLoughlin
    - McNamara
    - Mulligan
    - Murphy
    - O'Sullivan
    - O'Brien
    - O'Connor
    - O'Gallagher
    - O'Malley
    - O'Reilly
    - O'Shea
    - O'Sullivan
